site_name: Daphny
theme: readthedocs

nav:
  - Home: index.md
  - Absolute Value: AbsoluteValue_Doc.md
  - Find First Negative: FindFirstNegative_Doc.md
  - Factorial: Factorial_Doc.md
  - Tribonacci: Tribonacci_Doc.md

# 1. Add the Extensions section
markdown_extensions:
  # This enables the arithmatex extension
  - pymdownx.arithmatex:
      generic: true # Important! Use generic processing

# 2. Add the JavaScripts (The engine that draws the math)
extra_javascript:
  # Load the custom config file and the MathJax engine itself
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
